[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
rml-contracts = { path = "../../rml/crates/rml-contracts" }


[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(rml)', 'cfg(doc_cfg)'] }
